name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get --assume-yes install build-essential autoconf automake bison flex libncurses5-dev libreadline-dev texinfo liblz4 pkg-config texinfo libgmp-dev libmpfr-dev libmpc-dev libfreeimage-dev zlib1g-dev libusb-dev libudev-dev libexpat1-dev
    - name: Run
      run: |
        ./build-devkit.sh
